# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SmartCamera

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ObjectDetectionTop(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObjectDetectionTop(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObjectDetectionTop()
        x.Init(buf, n + offset)
        return x

    # ObjectDetectionTop
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObjectDetectionTop
    def Perception(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from SmartCamera.ObjectDetectionData import ObjectDetectionData
            obj = ObjectDetectionData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObjectDetectionTop
    def AreaCount(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from SmartCamera.CountData import CountData
            obj = CountData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObjectDetectionTop
    def AreaCountLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ObjectDetectionTop
    def AreaCountIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ObjectDetectionTopStart(builder): builder.StartObject(2)
def ObjectDetectionTopAddPerception(builder, perception): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(perception), 0)
def ObjectDetectionTopAddAreaCount(builder, areaCount): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(areaCount), 0)
def ObjectDetectionTopStartAreaCountVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ObjectDetectionTopEnd(builder): return builder.EndObject()
